
from unittest import TestSuite
from unittest import main as unitTestMain

from os import environ as osEnvironment
from os import sep as osSep

from pathlib import Path

from codeallybasic.UnitTestBase import UnitTestBase

from py2appsigner.DiskImageCreate import APP_SUFFIX
from py2appsigner.DiskImageCreate import DMG_SUFFIX
from py2appsigner.DiskImageCreate import DiskImageCreate
from py2appsigner.environment.DiskImageEnvironment import DiskImageEnvironment

from py2appsigner.environment.ExternalEnvironment import ENV_PROJECT
from py2appsigner.environment.ExternalEnvironment import ENV_PROJECTS_BASE

ENV_HOME:                str = 'HOME'
APPLICATION_NAME:        str = 'UmlDiagrammer'
RELATIVE_DIST_DIRECTORY: Path = Path('dist')
HOME_DIR:                str  = f'{osSep}users{osSep}hasii'
ALT_HOME_DIR:            str  = f'{osSep}users{osSep}ozzee'
PROJECTS_BASE:           str  = f'{HOME_DIR}{osSep}testProjectBase'

FQ_DIST_DIR:       Path = Path(f'{HOME_DIR}{osSep}{APPLICATION_NAME}{osSep}dist')
EXPECTED_APP_PATH: Path = Path(f'{FQ_DIST_DIR}{osSep}{APPLICATION_NAME}.{APP_SUFFIX}')
EXPECTED_DMG_PATH: Path = Path(f'{FQ_DIST_DIR}{osSep}{APPLICATION_NAME}.{DMG_SUFFIX}')


class TestDiskImageCreate(UnitTestBase):
    """
    Auto generated by the one and only:
        Gato Malo – Humberto A. Sanchez II
        Generated: 27 July 2026
    """

    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        osEnvironment[ENV_PROJECT]       = APPLICATION_NAME

    def setUp(self):
        super().setUp()

    def tearDown(self):
        super().tearDown()

    def testRelativeAppComputePath(self):
        osEnvironment[ENV_PROJECTS_BASE] = HOME_DIR

        environment:  DiskImageEnvironment = DiskImageEnvironment(applicationName=APPLICATION_NAME, distDirectory=RELATIVE_DIST_DIRECTORY)
        dskImgCreate: DiskImageCreate      = DiskImageCreate(environment=environment)

        actualPath: Path = dskImgCreate._computePath(baseName=APPLICATION_NAME, distDir=RELATIVE_DIST_DIRECTORY, suffix=APP_SUFFIX)

        self.assertEqual(actualPath, EXPECTED_APP_PATH, 'Incorrectly computed !!!')

    def testAbsoluteAppComputePath(self):
        """
        Change the home directory to make sure that we use the fully qualified one
        """
        osEnvironment[ENV_PROJECTS_BASE] = ALT_HOME_DIR
        environment:  DiskImageEnvironment = DiskImageEnvironment(
            applicationName=APPLICATION_NAME,
            distDirectory=FQ_DIST_DIR
        )
        dskImgCreate: DiskImageCreate      = DiskImageCreate(environment=environment)

        actualPath: Path = dskImgCreate._computePath(baseName=APPLICATION_NAME, distDir=FQ_DIST_DIR, suffix=APP_SUFFIX)

        self.assertEqual(actualPath, EXPECTED_APP_PATH, 'Incorrectly computed !!!')

    def testRelativeDmgComputePath(self):
        osEnvironment[ENV_PROJECTS_BASE] = HOME_DIR

        environment:  DiskImageEnvironment = DiskImageEnvironment(applicationName=APPLICATION_NAME, distDirectory=RELATIVE_DIST_DIRECTORY)
        dskImgCreate: DiskImageCreate      = DiskImageCreate(environment=environment)

        actualPath: Path = dskImgCreate._computePath(baseName=APPLICATION_NAME, distDir=RELATIVE_DIST_DIRECTORY, suffix=DMG_SUFFIX)

        self.assertEqual(actualPath, EXPECTED_DMG_PATH, 'Incorrectly computed !!!')

    def testAbsoluteDmgComputePath(self):
        """
        Change the home directory to make sure that we use the fully qualified one
        """
        osEnvironment[ENV_PROJECTS_BASE] = ALT_HOME_DIR
        environment:  DiskImageEnvironment = DiskImageEnvironment(
            applicationName=APPLICATION_NAME,
            distDirectory=FQ_DIST_DIR
        )
        dskImgCreate: DiskImageCreate      = DiskImageCreate(environment=environment)

        actualPath: Path = dskImgCreate._computePath(baseName=APPLICATION_NAME, distDir=FQ_DIST_DIR, suffix=DMG_SUFFIX)

        self.assertEqual(actualPath, EXPECTED_DMG_PATH, 'Incorrectly computed !!!')


def suite() -> TestSuite:
    import unittest

    testSuite: TestSuite = TestSuite()

    testSuite.addTest(unittest.defaultTestLoader.loadTestsFromTestCase(testCaseClass=TestDiskImageCreate))

    return testSuite


if __name__ == '__main__':
    unitTestMain()
